# Navigation Links
# To link a homepage section, specify the URL as a hash `#` followed by the
# section `id` defined in `content/_index.md`.

main:
  - name: Work
    url: /#selected
    weight: 10
  - name: Publications
    url: /#papers
    weight: 20
  - name: Approach
    url: /#approach
    weight: 30
  - name: News
    url: /#news
    weight: 40
  - name: Contact
    url: /#contact
    weight: 50
